In [1]:
import numpy as n
data=n.array([[1,2,3],[4,5,6]])
data


array([[1, 2, 3],
       [4, 5, 6]])

In [2]:
data=n.array([[1,2,3,4,5],[7,8,9,6,5],[5,6,8,3,4]])
data

array([[1, 2, 3, 4, 5],
       [7, 8, 9, 6, 5],
       [5, 6, 8, 3, 4]])

In [3]:
data=n.arange(1,10)
data

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
data=n.arange(1,100)
data

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [8]:
data=n.random.randint(1,40,size=(5,5))
data

array([[12, 29, 23, 15, 27],
       [30, 17, 36, 37,  9],
       [ 6, 20, 32, 32, 21],
       [30, 38, 33, 16, 23],
       [ 6, 32,  7, 12,  9]])

In [10]:
data=n.random.randint(1,50)
print(data)


46


In [25]:
import numpy as np
data=np.arange(0,40)
print(data)
data=data.reshape(4,10)
data

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [26]:
data=np.linspace(0,8,6)
data

array([0. , 1.6, 3.2, 4.8, 6.4, 8. ])

In [27]:
data=np.linspace(5,8)
data

array([5.        , 5.06122449, 5.12244898, 5.18367347, 5.24489796,
       5.30612245, 5.36734694, 5.42857143, 5.48979592, 5.55102041,
       5.6122449 , 5.67346939, 5.73469388, 5.79591837, 5.85714286,
       5.91836735, 5.97959184, 6.04081633, 6.10204082, 6.16326531,
       6.2244898 , 6.28571429, 6.34693878, 6.40816327, 6.46938776,
       6.53061224, 6.59183673, 6.65306122, 6.71428571, 6.7755102 ,
       6.83673469, 6.89795918, 6.95918367, 7.02040816, 7.08163265,
       7.14285714, 7.20408163, 7.26530612, 7.32653061, 7.3877551 ,
       7.44897959, 7.51020408, 7.57142857, 7.63265306, 7.69387755,
       7.75510204, 7.81632653, 7.87755102, 7.93877551, 8.        ])

In [29]:
data=np.linspace(6,10)
data

array([ 6.        ,  6.08163265,  6.16326531,  6.24489796,  6.32653061,
        6.40816327,  6.48979592,  6.57142857,  6.65306122,  6.73469388,
        6.81632653,  6.89795918,  6.97959184,  7.06122449,  7.14285714,
        7.2244898 ,  7.30612245,  7.3877551 ,  7.46938776,  7.55102041,
        7.63265306,  7.71428571,  7.79591837,  7.87755102,  7.95918367,
        8.04081633,  8.12244898,  8.20408163,  8.28571429,  8.36734694,
        8.44897959,  8.53061224,  8.6122449 ,  8.69387755,  8.7755102 ,
        8.85714286,  8.93877551,  9.02040816,  9.10204082,  9.18367347,
        9.26530612,  9.34693878,  9.42857143,  9.51020408,  9.59183673,
        9.67346939,  9.75510204,  9.83673469,  9.91836735, 10.        ])

# bultin functions

In [35]:
import numpy as np
data=np.ones((4,3),int)
print(data)

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


In [38]:
data=np.zeros((4,4),int)
data

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [39]:
n=np.array([1,2,3,4,5,6])
n1=np.array([1,2,3,4,5,6])
n+n1


array([ 2,  4,  6,  8, 10, 12])

In [40]:
n=np.array([1,2,3,4,5,6])
n1=np.array([1,2,3,4,5,6])
n-n1


array([0, 0, 0, 0, 0, 0])

In [41]:
n=np.array([1,2,3,4,5,6])
n1=np.array([1,2,3,4,5,6])
n*n1


array([ 1,  4,  9, 16, 25, 36])

In [42]:
n=np.array([1,2,3,4,5,6])
n1=np.array([1,2,3,4,5,6])
n**n1


array([    1,     4,    27,   256,  3125, 46656], dtype=int32)

In [43]:
n=np.array([1,2,3,4,5,6])
n1=np.array([1,2,3,4,5,6])
n.dot(n1)

91

In [44]:
n=np.array([1,2,3,4,5,6])
n1=np.array([n,n*2])
n1


array([[ 1,  2,  3,  4,  5,  6],
       [ 2,  4,  6,  8, 10, 12]])

In [45]:
n=np.array([1,2,3,4,5,6])
n1=np.array([n,n**3])
n1


array([[  1,   2,   3,   4,   5,   6],
       [  1,   8,  27,  64, 125, 216]])

In [46]:
n=np.array([1,2,3,4,5,6])
n1=np.array([n,pow(n,3)])
n1


array([[  1,   2,   3,   4,   5,   6],
       [  1,   8,  27,  64, 125, 216]])

In [50]:
n=np.array([[1,2,3],[5,8,6]])
n.T


array([[1, 5],
       [2, 8],
       [3, 6]])

In [51]:
n=np.array([[1, 5],
       [2, 8],
       [3, 6]])
n.transpose()

array([[1, 2, 3],
       [5, 8, 6]])

In [53]:
n=np.array([1,2,3,4,5,6,7])
n.dtype

dtype('int32')

In [54]:
n.astype

<function ndarray.astype>

In [55]:
data=np.random.randint(1,20,size=(4,4))
data

array([[ 3, 12,  1,  8],
       [ 7,  9, 10,  9],
       [ 3, 17, 12, 13],
       [ 6, 15,  5,  4]])

In [56]:
data.min()

1

In [57]:
data.max()

17

In [58]:
data.sum()

134

In [59]:
data.mean()

8.375

In [60]:
data.std()

4.470388685561916

In [61]:
data.argmin()

2

In [62]:
data.argmax()

9

In [63]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [68]:
data=np.array([1,2,3,6])
np.diag(data)

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 6]])

In [70]:
data=np.array([1,2,3,6]*3)
data

array([1, 2, 3, 6, 1, 2, 3, 6, 1, 2, 3, 6])

In [72]:
data=np.repeat([1,2,3,4],3)
data

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])