In [40]:
a=10
print(a)

10


# Numpy

In [2]:
import numpy as np
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [3]:
data = np.array([[1,2,3,4],[2,3,4,5],[6,7,5,5]])
data

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [6, 7, 5, 5]])

In [4]:
data=np.arange(1,20)
data

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [5]:
data = np.random.randint(1,50)
data

11

In [6]:
data = np.random.randint(1,50,size=(4,4))
data

array([[22, 12, 17, 10],
       [37, 25, 27, 44],
       [ 9, 25, 38, 11],
       [11,  1,  6, 20]])

In [26]:
import numpy as np
data = np.arange(0,100)
print(data)
data = data.reshape(10,10)
data

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [7]:
data.min()
data.max()
data.sum()
data.mean()
data.std()

11.998535066832117

In [8]:
data = np.array([1,2,3,4])
data1 = np.array([6,4,8,9])
data.dot(data1)

74

In [9]:
data = np.ones((3,3),int)
data=data.diag([2,2,2])
data

AttributeError: 'numpy.ndarray' object has no attribute 'diag'

In [10]:

data = np.zeros((4,4),int)
data1 = data.diag([2,2,2])
data1

AttributeError: 'numpy.ndarray' object has no attribute 'diag'

In [11]:
data = np.arange(0,9)
data = data.reshape((3,3))
#print(data)
data = np.diag(data)
print(data)

[0 4 8]


In [12]:
data=np.array([[1,2,3],[4,5,6]])
print(data.T)

[[1 4]
 [2 5]
 [3 6]]


In [13]:
data=np.array([[1,2,3],[5,6,7]])
data1=data.transpose()
print(data1)

[[1 5]
 [2 6]
 [3 7]]


In [14]:
data=np.arange(0,9)
data=data.reshape((3,3))
print(data)
data1=np.mean(data)
print(data1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
4.0


In [15]:
data=np.arange(0,9)
data=data.reshape((3,3))
print(data)
data1=np.max(data)
print(data1)
data2=np.min(data)
print(data2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
8
0


In [16]:
data1=np.array([1,2,3,4])
data2=np.array([5,6,7,8])
data=np.array(data1+data2)
print(data)

[ 6  8 10 12]


In [17]:
data1=np.array([1,2,3,4])
data2=np.array([5,6,7,8])
data=np.array(data1-data2)
print(data)

[-4 -4 -4 -4]


In [18]:
data1=np.array([1,2,3,4])
data2=np.array([5,6,7,8])
data=np.array(data1*data2)
print(data)

[ 5 12 21 32]


In [19]:
import numpy as np
data1=np.array([1,2,3,4])
data2=np.array([5,6,7,8])
data=data1.dot(data2)
print(data)

70
