### Python Programming Language Types and Sequences

In [1]:
line = 'Welcome to Applied Data Science'
type(line)

str

In [2]:
a = 10
type(a)

int

In [3]:
percentage = 98.43
type(percentage)

float

In [4]:
marks = [21,20,25,19,15]
type(marks)

list

In [5]:
marks.append(11)
marks

[21, 20, 25, 19, 15, 11]

In [6]:
marks

[21, 20, 25, 19, 15, 11]

In [7]:
for i in marks:
    print(i)

21
20
25
19
15
11


In [11]:
j = 0
while (j != len(marks)):
    print(marks[j])
    j = j + 1

21
20
25
19
15
11


In [12]:
marks

[21, 20, 25, 19, 15, 11]

In [14]:
marks.sort()
marks

[11, 15, 19, 20, 21, 25]

In [15]:
[1,4,7,9] + [1,3,6,4]

[1, 4, 7, 9, 1, 3, 6, 4]

In [16]:
[6]*3

[6, 6, 6]

In [20]:
i in marks

True

In [21]:
line

'Welcome to Applied Data Science'

In [22]:
print(line[0])

W


In [23]:
print(line[0:7])

Welcome


In [24]:
print(line[12:])

pplied Data Science


In [25]:
print(line[11:])

Applied Data Science


In [28]:
fname = 'Ambika'
lname = 'Puvvula'
#name = fname + lname
print(fname+' '+lname)

Ambika Puvvula


In [29]:
'Ambi' in fname

True

In [34]:
'ula' in lname

True

### Dictionaries

In [35]:
d = {'Ambika':'ambikapuvvula@gmail.com','Anil':'anilkumar.puvvula1999@gmail.com'}
d

{'Ambika': 'ambikapuvvula@gmail.com',
 'Anil': 'anilkumar.puvvula1999@gmail.com'}

In [36]:
d['Ambika']

'ambikapuvvula@gmail.com'

In [41]:
d['jyothi']='jyothikrishna.puvvula@gmail.com'
d

{'Ambika': 'ambikapuvvula@gmail.com',
 'Anil': 'anilkumar.puvvula1999@gmail.com',
 'jyothi': 'jyothikrishna.puvvula@gmail.com'}

In [42]:
for name in d:
    print(name)

Ambika
Anil
jyothi


In [43]:
d.values()

dict_values(['ambikapuvvula@gmail.com', 'anilkumar.puvvula1999@gmail.com', 'jyothikrishna.puvvula@gmail.com'])

In [44]:
for mail in d.values():
    print(mail)

ambikapuvvula@gmail.com
anilkumar.puvvula1999@gmail.com
jyothikrishna.puvvula@gmail.com


In [45]:
for name,mail in d.items():
    print(name)
    print(mail)

Ambika
ambikapuvvula@gmail.com
Anil
anilkumar.puvvula1999@gmail.com
jyothi
jyothikrishna.puvvula@gmail.com


### Tuples

In [46]:
t = ('Ambika','Puvvula','ambikapuvvula@gmail.com')
t

('Ambika', 'Puvvula', 'ambikapuvvula@gmail.com')

In [49]:
(fname,lname,mail) = t

In [50]:
fname

'Ambika'

In [51]:
lname

'Puvvula'

In [52]:
mail

'ambikapuvvula@gmail.com'

In [54]:
s = 'Hi {} This is ur mail id {}'.format(d.keys(),d['jyothi'])
s

"Hi dict_keys(['Ambika', 'Anil', 'jyothi']) This is ur mail id jyothikrishna.puvvula@gmail.com"

### Reading and writing csv files

In [75]:
import csv
with open('Files/data.csv','rt')as f:
  data = csv.reader(f)
  for row in data:
        print(row)

['Programming language', 'Designed by', 'Appeared', 'Extension']
['Python', 'Guido van Rossum', '1991', '.py']
['Java', 'James Gosling', '1995', '.java']
['C++', 'Bjarne Stroustrup', '1983', '.cpp']


In [78]:
import csv
with open('Files/data.csv') as data:
    data=list(csv.DictReader(data))
    print(type(csv.DictReader(data)))

<class 'csv.DictReader'>


In [79]:
print(type(data))

<class 'list'>


In [80]:
print(len(data))

3


In [81]:
print(data[0].keys())

odict_keys(['Programming language', 'Designed by', 'Appeared', 'Extension'])


In [82]:
data

[OrderedDict([('Programming language', 'Python'),
              ('Designed by', 'Guido van Rossum'),
              ('Appeared', '1991'),
              ('Extension', '.py')]),
 OrderedDict([('Programming language', 'Java'),
              ('Designed by', 'James Gosling'),
              ('Appeared', '1995'),
              ('Extension', '.java')]),
 OrderedDict([('Programming language', 'C++'),
              ('Designed by', 'Bjarne Stroustrup'),
              ('Appeared', '1983'),
              ('Extension', '.cpp')])]

### Date and Time

In [84]:
import datetime as dt
import time as t
t.time()

1562617753.726145

In [86]:
ds = dt.datetime.fromtimestamp(t.time())
ds

datetime.datetime(2019, 7, 8, 14, 30, 31, 12614)

In [88]:
ds.year

2019

In [89]:
ds.month

7

In [90]:
ds.day

8

In [92]:
ds.hour

14

In [93]:
ds.minute

30

In [94]:
ds.second

31

In [101]:
# Want to know the date of 100 days ago
days = dt.timedelta(days = 10)
days

datetime.timedelta(days=10)

In [102]:
tdate = dt.date.today()
tdate

datetime.date(2019, 7, 8)

In [103]:
hdays = tdate - days
hdays

datetime.date(2019, 6, 28)

In [104]:
import time
ltime = time.localtime(time.time())
ltime

time.struct_time(tm_year=2019, tm_mon=7, tm_mday=8, tm_hour=14, tm_min=38, tm_sec=32, tm_wday=0, tm_yday=189, tm_isdst=1)

In [105]:
import time
ltime = time.asctime(time.localtime(time.time()))
ltime

'Mon Jul  8 14:40:00 2019'

### Time Module Methods

time() - returns floating point value in seconds

asctime(time) - It takes the tuple returned by localtime() as parameter. It returns a 24 character string.

sleep(time) - The execution will be stopped for the given interval of time

strptime(String,format) - It returns an tuple with 9 time attributes. It receives an String of date and a format.

gtime()/gtime(sec) - It returns struct_time which contains 9 time attributes. In case seconds are not specified it takes current second from epoch.

mktime() - It returns second in floating point since epoch.

strftime(format)/strftime(format,time) - It returns time in particular format. If time is not given, current time in seconds is fetched.

In [106]:
import time
lt = time.localtime(time.time())
lt

time.struct_time(tm_year=2019, tm_mon=7, tm_mday=8, tm_hour=14, tm_min=49, tm_sec=3, tm_wday=0, tm_yday=189, tm_isdst=1)

In [107]:
import time
lt = time.asctime(time.localtime(time.time()))
lt

'Mon Jul  8 14:49:20 2019'

In [112]:
import time
localtime = time.asctime(time.localtime(time.time()))
print(localtime)
time.sleep(100)
localtime = time.asctime(time.localtime(time.time()))
print(localtime)

Mon Jul  8 14:54:51 2019
Mon Jul  8 14:56:31 2019


In [115]:
import time  
timestrip = time.strptime("26 Jun 14", "%d %b %y")  
print(timestrip) 


time.struct_time(tm_year=2014, tm_mon=6, tm_mday=26, tm_hour=0, tm_min=0, tm_sec=0, tm_wday=3, tm_yday=177, tm_isdst=-1)


In [117]:
import time  
print(time.gmtime()) 

time.struct_time(tm_year=2019, tm_mon=7, tm_mday=8, tm_hour=20, tm_min=59, tm_sec=7, tm_wday=0, tm_yday=189, tm_isdst=0)


In [118]:
import time  
t = (2019, 8, 15, 17, 3, 38, 1, 48, 0)  
second = time.mktime( t )  
print(second)

1565913818.0


In [119]:
import time  
t = (2019, 8, 15, 17, 3, 38, 1, 48, 0)  
t = time.mktime(t)  
print(time.strftime("%b %d %Y %H:%M:%S", time.gmtime(t)))  

Aug 16 2019 00:03:38


### Numpy

Numpy Stands for Numerical Python.

It is a library consists of multi dimensional array objects

Using this mathematical and logical operations on arrays can be performed

In [121]:
import numpy as np
x = [1,4,7,9,2]
y = np.array(x)
print(y)

[1 4 7 9 2]


In [126]:
# creating 2D arrays
import numpy as np
m = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(m)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [127]:
m.shape

(3, 3)

In [128]:
import numpy as np
q = np.arange(0,25,2)
q

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])