### Pandas
- Derived from PANel DAta -- Economerics from Multidimensional Data
- Developed by Wes Mckinney
- Open Source Python Library 
- Used as data Manupulation and Analysis Tool

### Installation Of Pandas
- For Windows
    - pip install pandas
- For Linux 
    - sudo apt-get install python3 pandas

### Data Structures in Python Pandas
- Data Frame
- Series

### Pandas Series
- Creating Series -- pandas.Series(data,index,datatype)
- Indexing Series

### Data Frames
- Creating Data Frames from Dictionary
- Import CSV data as pandas dataframes
- Reading and Summarizing data Frames
- Sorting Data Frames

In [1]:
## Series is a 1D array holds int,float,str data types
import pandas as pd
s = pd.Series([1,2,3])
s

0    1
1    2
2    3
dtype: int64

In [17]:
a = pd.Series(['abc','def','ghi',2,9.0,'s'])
a

0    abc
1    def
2    ghi
3      2
4      9
5      s
dtype: object

In [3]:
z = pd.Series([12.0,34.0,78.6])
z

0    12.0
1    34.0
2    78.6
dtype: float64

In [11]:
q = pd.Series([1,2,3,4],index = ['a','b','c','e'])
q

a    1
b    2
c    3
e    4
dtype: int64

In [12]:
q[1:3]

b    2
c    3
dtype: int64

In [13]:
q[1:]

b    2
c    3
e    4
dtype: int64

In [14]:
q[:]

a    1
b    2
c    3
e    4
dtype: int64

In [4]:
import pandas as pd
num = int(input("Enter Number: "))
s = [i**2 for i in range(1,num+1)]
n = pd.Series(s)
type(n)
n

Enter Number: 9


0     1
1     4
2     9
3    16
4    25
5    36
6    49
7    64
8    81
dtype: int64

In [14]:
# Data Frames - 2D Arrays mostly used in Data analysis
# ways of Creating data frames
    # Created using dictionary
    # json Objects
    # Reading from text,Csv files

In [1]:
# Created using list 
import pandas as pd
data = [['Ambika','Trainer'],['Amrutha','Finance'],['Keerthi',"HR"]]
d = pd.DataFrame(data,columns=['Name','Designation'])
#print(d)
d

Name Designation
0   Ambika     Trainer
1  Amrutha     Finance
2  Keerthi          HR

In [6]:
# Created using dictioanry
info = {'Name':'Ambika','Clg':'PVP','Branch':'ECE','Year':'3rd'}
data = {'Name':'Archana','Clg':'GEC','Branch':'CSE'}
details = {'Name':'Sahithi','Clg':'VRSEC','Branch':'CSE'}
s = pd.DataFrame([info,data,details],index = ['Trainer Name','College Location','Branch'])
a = pd.DataFrame([info,data,details],columns = ['Trainer Name','College Location','Branch'])
s
#a
s.head()

Name    Clg Branch Year
Trainer Name       Ambika    PVP    ECE  3rd
College Location  Archana    GEC    CSE  NaN
Branch            Sahithi  VRSEC    CSE  NaN

### Extract data using loc and iloc attributes
- loc --> used to give index data
- iloc --> used to give index value

In [9]:
s.loc['Branch']
#type(s)

Name      Sahithi
Clg         VRSEC
Branch        CSE
Year          NaN
Name: Branch, dtype: object

In [37]:
type(s)

pandas.core.frame.DataFrame

In [43]:
s.iloc[0]

Name      Ambika
Clg          PVP
Branch       ECE
Year         3rd
Name: Trainer Name, dtype: object

In [40]:
type(s)

pandas.core.frame.DataFrame

In [45]:
s['fg']='hjk'
s

Name    Clg Branch Year   fg
Trainer Name       Ambika    PVP    ECE  3rd  hjk
College Location  Archana    GEC    CSE  NaN  hjk
Branch            Sahithi  VRSEC    CSE  NaN  hjk

In [12]:
# Converting Rows to columns and Columns to Rows
s.T

Trainer Name College Location   Branch
Name         Ambika          Archana  Sahithi
Clg             PVP              GEC    VRSEC
Branch          ECE              CSE      CSE
Year            3rd              NaN      NaN

In [18]:
s.T.loc['Branch']

Trainer Name        ECE
College Location    CSE
Branch              CSE
Name: Branch, dtype: object

In [20]:
s.T.iloc[0]

Trainer Name         Ambika
College Location    Archana
Branch              Sahithi
Name: Name, dtype: object

In [19]:
type(s.T.loc['Branch'])

pandas.core.series.Series

In [21]:
type(s.T.iloc[0])

pandas.core.series.Series

In [23]:
s

Name    Clg Branch Year
Trainer Name       Ambika    PVP    ECE  3rd
College Location  Archana    GEC    CSE  NaN
Branch            Sahithi  VRSEC    CSE  NaN

In [25]:
s.drop('Branch')

Name  Clg Branch Year
Trainer Name       Ambika  PVP    ECE  3rd
College Location  Archana  GEC    CSE  NaN

In [26]:
s

Name    Clg Branch Year
Trainer Name       Ambika    PVP    ECE  3rd
College Location  Archana    GEC    CSE  NaN
Branch            Sahithi  VRSEC    CSE  NaN

In [27]:
branches = s['Branch']
branches

Trainer Name        ECE
College Location    CSE
Branch              CSE
Name: Branch, dtype: object

In [30]:
branches += '2'
branches

Trainer Name        ECECSE22
College Location    CSECSE22
Branch              CSECSE22
Name: Branch, dtype: object

In [31]:
s

Name    Clg    Branch Year
Trainer Name       Ambika    PVP  ECECSE22  3rd
College Location  Archana    GEC  CSECSE22  NaN
Branch            Sahithi  VRSEC  CSECSE22  NaN

# Reading CSV Files
import pandas as pd
path = 'Income.csv'
data = pd.read_csv(path)
data

In [5]:
# Extract Income of all States
for row in data.values:
    print(row[1],':',row[-2])

Alabama : 43464
Alaska : 63648
Arizona : 47044
Arkansas : 39018
California : 57020


In [7]:
# Average Income of Arizona State
sum = 0
for i in range(2,11):
    sum = sum + data.values[2][i]
sum/len(data.values[2][2:11])

47214.77777777778

## Pandas
- Why we use pandas
- How the name comes
- Introduced by
- Where we used
- Installation
- Data frames
    - Data Frames
    - Series
        - Creating Data Frames
        - Indexing Data Frames
        - loc
        - iloc


In [1]:
# 1 dimensional data
import pandas as pd
a = pd.Series([1,2,3])
a

0    1
1    2
2    3
dtype: int64

In [2]:
s = pd.Series(['abc','def'])
s

0    abc
1    def
dtype: object

In [5]:
f = pd.Series([1.0,2.5,3.7],index=['a','b','c'])
f

a    1.0
b    2.5
c    3.7
dtype: float64

In [9]:
n = int(input("Enter Number: "))
q = [i**2 for i in range(1,n+1)]
e = [i for i in range(1,n+1)]
w = pd.Series(q,index = [e])
w

Enter Number: 20


1       1
2       4
3       9
4      16
5      25
6      36
7      49
8      64
9      81
10    100
11    121
12    144
13    169
14    196
15    225
16    256
17    289
18    324
19    361
20    400
dtype: int64

In [16]:
# Created using Lists
data = [['Sneha','Younger Sister'],['Buddy','Little Younger Brother'],['Keerthi','Younger Sister'],['Preethi','Sister'],['Eshwar','Brother'],['Lavanya','Sister']]
s = pd.DataFrame(data,columns=['Name','Relation'])
d = pd.DataFrame(data,columns=['Name','Relation'],index=[1,2,3,4,5,6])
s
d
s.head()

Name                Relation
0    Sneha          Younger Sister
1    Buddy  Little Younger Brother
2  Keerthi          Younger Sister
3  Preethi                  Sister
4   Eshwar                 Brother

In [75]:
q = {'Name':'Ambika','Clg':'Vishnu','Branch':'ECE'}
a = {'Name':'Archana','Clg':'GEC'}
z = {'Name':'Vidya'}
w = pd.DataFrame([q,a,z],columns=['Name','Clg','Branch'],index=['One','Two','Three'])
w

Name     Clg Branch
One     Ambika  Vishnu    ECE
Two    Archana     GEC    NaN
Three    Vidya     NaN    NaN

In [76]:
# loc --> by using index value
# iloc --> by using index number
w
w.iloc[0]
w.loc['One']

Name      Ambika
Clg       Vishnu
Branch       ECE
Name: One, dtype: object

In [78]:
w['Year'] = '2nd'
w

Name     Clg Branch Year
One     Ambika  Vishnu    ECE  2nd
Two    Archana     GEC    NaN  2nd
Three    Vidya     NaN    NaN  2nd

In [80]:
u = w.T
u

One      Two  Three
Name    Ambika  Archana  Vidya
Clg     Vishnu      GEC    NaN
Branch     ECE      NaN    NaN
Year       2nd      2nd    2nd

In [82]:
u.loc['Name']

One       Ambika
Two      Archana
Three      Vidya
Name: Name, dtype: object

In [84]:
u.iloc[0]

One       Ambika
Two      Archana
Three      Vidya
Name: Name, dtype: object

In [88]:
w
w.drop(['Three'])

Name     Clg Branch Year
One   Ambika  Vishnu    ECE  2nd
Two  Archana     GEC    NaN  2nd

In [26]:
a = "archana"
n = iter(a)
print(next(n))
print(next(n))
print(next(n))
print(next(n))
print(next(n))
print(next(n))
print(next(n))
print(next(n))

a
r
c
h
a
n
a


StopIteration: 

In [28]:
import numpy as n
data = n.array([[1,2,3],[3,4,5]])
data

array([[1, 2, 3],
       [3, 4, 5]])

In [33]:
data.shape
data.size
data.reshape(3,2)

array([[1, 2],
       [3, 3],
       [4, 5]])

In [34]:
data1 = n.arange(0,50)
data1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [43]:
data2 = data1.reshape(5,10)
data2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [40]:
data2.reshape(10,5)
data2.shape
data2.size

50

In [45]:
data3 = n.random.randint(1,20, size=(2,2))
data3

array([[19,  8],
       [18,  6]])

In [47]:
data2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [48]:
data2.max()

49

In [49]:
data2.min()

0

In [50]:
data2.sum()

1225

In [53]:
data2.mean()

24.5

In [52]:
data2.std()

14.430869689661812

In [54]:
data2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [55]:
data3

array([[19,  8],
       [18,  6]])

In [58]:
data3*data3

array([[361,  64],
       [324,  36]])

In [59]:
zeros = n.zeros((3,4))
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [60]:
zeros = n.zeros((3,4),int)
zeros

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [63]:
one = n.ones((4,4),int)
one

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [66]:
an = n.vstack([one,one+3])
an

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4]])

In [67]:
h = n.hstack([zeros,zeros+19])
h

array([[ 0,  0,  0,  0, 19, 19, 19, 19],
       [ 0,  0,  0,  0, 19, 19, 19, 19],
       [ 0,  0,  0,  0, 19, 19, 19, 19]])